### ISSUE TITLE
Cant get server info [com.ibasco.agql.core.exceptions.ReadTimeoutException]

### ISSUE THREAD

**Issue by Xoma163** [DarkAtra/v-rising-discord-bot#112]
Hello

`/add-server server-hostname:46.0.192.108 server-query-port:9876`
<details>
  <summary>image</summary>
<img src="https://github.com/DarkAtra/v-rising-discord-bot/assets/35608430/65c4869f-4d3c-4e48-88f3-b0928d18f1b1">

  
</details>

What's wrong? I can status my server in monitoring [here](https://www.battlemetrics.com/servers/vrising/27596640)

**Comment by DarkAtra** [comment]
you've used the wrong port. the correct query port is: `9877`

**Comment by Xoma163** [comment]
> you've used the wrong port. the correct query port is: `9877`

Oh sorry, my bad.
It works. Thank you!

**Comment by adthonb** [comment]
I got the same message and checked that port 9877 could be accessed but your bot can't query my server. Should I set `ListOnSteam` option to `true` ?

**Comment by adthonb** [comment]
I am sure 100% using the correct port. I set my server from scrap and config `ServerHostSettings.json` by myself. I can query `v-rising-discord-bot-companion` API normally. I just think `ListOnSteam` option will cause this issue

**Comment by DarkAtra** [comment]
> I am sure 100% using the correct port. I set my server from scrap and config `ServerHostSettings.json` by myself. I can query `v-rising-discord-bot-companion` API normally. I just think `ListOnSteam` option will cause this issue

the bot companion has nothing to do with the query port though. can you maybe elaborate what exactly you're trying to do atm?

**Comment by adthonb** [comment]
I want to use your Jarvis bot to show server status and kill feed. I got this message:
```
CompletionException: 
com.ibasco.agql.core.exceptions.MaxAttemptsReachedException:
com.ibasco.agql.core.exceptions.ReadTimeoutException
```
You can test this IP 141.98.19.254:9877

**Comment by DarkAtra** [comment]
> I want to use your Jarvis bot to show server status and kill feed. I got this message:
> 
> ```
> CompletionException: 
> com.ibasco.agql.core.exceptions.MaxAttemptsReachedException:
> com.ibasco.agql.core.exceptions.ReadTimeoutException
> ```
> 
> You can test this IP 141.98.19.254:9877

I want to give a little context first before diving into what's wrong with your config.
There are two ports that the discord bot can make use of: `server-query-port` and `server-api-port`
The `server-query-port` is a UDP port that exposes everything that is usually visible in the in-game server browser (the server name, description, settings and the player list).
The `server-api-port` is a V Rising specific HTTP port where the server usually exposes metrics. The bot-companion uses that port to expose additional data for the activity and player feed.

With that out of the way, you'll want to use the **query port** for the status embed. Note that `9877` is not correct as this is your servers **api port**. Refer to my previous comment on how to find the **query port**: https://github.com/DarkAtra/v-rising-discord-bot/issues/112#issuecomment-2124693830.

Regarding the bot companion: simply follow [this guide](https://vrising.darkatra.dev/bot-companion.html#connecting-the-bot-companion-to-the-discord-bot) and use `9877` as `server-api-port` and `141.98.19.254` as `server-api-hostname`.

**Comment by adthonb** [comment]
Sorry to make you confuse. My API port is 25570. My query port is 9877. This is my server https://www.battlemetrics.com/servers/vrising/27536305 but the IP is not correct cause I changed from VPS to a Dedicated server.

This is my `ServerHostSettings.json`
```
{
  "Name": "[TH]Meow Meow x1.5 Weekend Raid",
  "Description": "อ่านกฎใน Discord https://discord.gg/tcr3TN3m6c",
  "Port": 9876,
  "QueryPort": 9877,
  "MaxConnectedUsers": 100,
  "MaxConnectedAdmins": 4,
  "ServerFps": 30,
  "SaveName": "world1",
  "Password": "",
  "Secure": true,
  "ListOnSteam": false,
  "ListOnEOS": true,
  "AutoSaveCount": 20,
  "AutoSaveInterval": 120,
  "CompressSaveFiles": true,
  "GameSettingsPreset": "",
  "GameDifficultyPreset": "",
  "AdminOnlyDebugEvents": true,
  "DisableDebugEvents": false,
  "API": {
    "Enabled": true,
    "BindPort": 25570
  },
  "Rcon": {
    "Enabled": false,
    "Port": 25575,
    "Password": ""
  }
}
```

**Comment by DarkAtra** [comment]
> Sorry to make you confuse. My API port is 25570. My query port is 9877. This is my server https://www.battlemetrics.com/servers/vrising/27536305 but the IP is not correct cause I changed from VPS to a Dedicated server.
> 
> This is my `ServerHostSettings.json`
> 
> ```
> {
>   "Name": "[TH]Meow Meow x1.5 Weekend Raid",
>   "Description": "อ่านกฎใน Discord https://discord.gg/tcr3TN3m6c",
>   "Port": 9876,
>   "QueryPort": 9877,
>   "MaxConnectedUsers": 100,
>   "MaxConnectedAdmins": 4,
>   "ServerFps": 30,
>   "SaveName": "world1",
>   "Password": "",
>   "Secure": true,
>   "ListOnSteam": false,
>   "ListOnEOS": true,
>   "AutoSaveCount": 20,
>   "AutoSaveInterval": 120,
>   "CompressSaveFiles": true,
>   "GameSettingsPreset": "",
>   "GameDifficultyPreset": "",
>   "AdminOnlyDebugEvents": true,
>   "DisableDebugEvents": false,
>   "API": {
>     "Enabled": true,
>     "BindPort": 25570
>   },
>   "Rcon": {
>     "Enabled": false,
>     "Port": 25575,
>     "Password": ""
>   }
> }
> ```

I just double checked:
* i don't get a response when querying `141.98.19.254:9877`
* also no response for `45.136.254.195:9877` (which is likely expected, right?)

As you already said this might be caused by the fact that your server is not listed on steam. However, i'd have to verify that first, which i can't do right now.

Also, it would simplify debugging a lot if you could link me your current server on battlemetrics.

**Comment by DarkAtra** [comment]
@adthonb i've just confirmed that `ListOnSteam` has to be `true` - the server doesn't allow connections to the query port if it's disabled. i'll add that to the documentation

**Comment by adthonb** [comment]
Hello, I got a new error message. `NullPointerException: null` 

Before this error, Jarvis posts only 2 status messages. No updated PvP Kill Feed update. No Status update.
My server https://www.battlemetrics.com/servers/vrising/27710147

**Comment by DarkAtra** [comment]
> Hello, I got a new error message. `NullPointerException: null`
> 
> Before this error, Jarvis posts only 2 status messages. No updated PvP Kill Feed update. No Status update. My server https://www.battlemetrics.com/servers/vrising/27710147

Seems like i forgot to add the runtime hints for some bot companion related classes. This release should fix the issue: https://github.com/DarkAtra/v-rising-discord-bot/releases/tag/v2.9.2.

**Comment by DarkAtra** [comment]
@adthonb just released https://github.com/DarkAtra/v-rising-discord-bot-companion/releases/tag/v0.5.3 as a fix for the mysterious 58th vblood

**Comment by adthonb** [comment]
@DarkAtra Hello, yesterday I got a new error message: `NullPointerException: null`. I try to update the status from DEACTIVE to ACTIVE but it still loops back to the failure state.

This is my server: https://www.battlemetrics.com/servers/vrising/27710147

**Comment by DarkAtra** [comment]
> @DarkAtra Hello, yesterday I got a new error message: `NullPointerException: null`. I try to update the status from DEACTIVE to ACTIVE but it still loops back to the failure state.
> 
> This is my server: https://www.battlemetrics.com/servers/vrising/27710147

did you update the server side plugin to v0.5.7?

**Comment by DarkAtra** [comment]
> > > @DarkAtra Hello, yesterday I got a new error message: `NullPointerException: null`. I try to update the status from DEACTIVE to ACTIVE but it still loops back to the failure state.
> > > This is my server: https://www.battlemetrics.com/servers/vrising/27710147
> > 
> > did you update the server side plugin to v0.5.7?
> 
> I had updated to v0.5.7, and after that I got this message:
> `CompletionException: com.ibasco.agql.core.exceptions.MaxAttemptsReachedException: com.ibasco.agql.core.exceptions.ReadTimeoutException`

i'll investigate the issue when i'm home

**Comment by DarkAtra** [comment]
@adthonb i rolled out a fix
